### PR TITLE
Add Avro rendering of enums

### PR DESCRIPTION
**Pull request by jack-davies**
Hi Tikhon.

I've been trying out your recent enum additions to theta. I'm a big fan. Not sure if this is intentional on your part, but I noticed Avro rendering is not implemented for enums:

```
Error converting to/from Avro:

Cannot export the chosen type as a top-level Avro schema:

backend.MessageFrom

Only records and variants can be exported as stand-alone Avro schemas.
```

A couple of new cases in `Types.hs`, presented in this PR, and I get an Avro enum as expected:

```
{"aliases":[],"doc":"Generated with Theta 1.0.0.0\nType hash: 5bf3f93d60fb583f8635fa98145fe6eb","name":"backend.MessageFrom","symbols":["AGENT","CLIENT"],"type":"enum"}
```

If you'd be happy to accept a patch, I can add some test cases and clean up "records only" references in the docs.

### CODE REVIEW

**Comment by pasunboneleve** [comment]
Does the enum machinery include the Python code generation/bindings? We will need these to be in sync so that Python too could read and write from these definitions.

**Comment by TikhonJelvis** [comment]
> Does the enum machinery include the Python code generation/bindings? We will need these to be in sync so that Python too could read and write from these definitions.

Yeah, it supports Python, generating an `Enum` class.

```
enum Foo = Bar | Baz
```

gets us:

```
class Foo(Enum):
    Bar = 0
    Baz = 1

    ...
```

Thanks to how the Avro format works, it will have the same *binary* representation as `type Foo = Bar | Baz`, even though the Avro *schema* for it is different. However, this might end up working differently in future formats (eg JSON) or when I add schema resolution.

**Comment by TikhonJelvis** [comment]
@jack-davies Thanks for the PR! Glad you're finding enums useful.

Adding enums to the supported top-level types seems reasonable and I'd be happy to merge a patch for it. I don't remember why I have this restriction on top-level schemas—I had some specific reason three years ago, but looking over the [Avro specification][1] I can't figure out what that reason was. It might make sense to let *any* type be rendered as a top-level schema, but that might affect some other commands (eg the output of `theta avro all`), so it seems easier to just add enums for now.

Looks like my GitHub Actions configuration doesn't run on PRs from forked repos. I'm guessing that's because I set it to run on `push` and not on `pull_request`. I'm going to change that back now; could you try merging `stage` into your branch once I do that? Thanks!

[1]: https://avro.apache.org/docs/current/spec.html

**Comment by jack-davies** [comment]
> It might make sense to let any type be rendered as a top-level schema, but that might affect some other commands (eg the output of theta avro all), so it seems easier to just add enums for now.

This is a really attractive suggestion that I hadn't considered until you mentioned it-- I have done a quick test locally to allow any type to be rendered as a top-level schema and it all seems to behave well and according to the Avro spec. I'll push something to another branch for comparison.

In the mean time I've merged in your changes in `stage`, it looks like your tests are already very comprehensive so if we were to scope this just to enums then all that's left here is to update the docs.

**Comment by TikhonJelvis** [comment]
Yeah, that sounds reasonable to me. Probably not too many places to update in the documentation either.

**Comment by TikhonJelvis** [comment]
Oh, I guess the `theta avro all` command would [need to be updated][updated]. I have some tests for that command in [`test/avro`][avro] and adding an enum there should catch that. If you don't have Nix handy to run those tests, I can help with that.

Also, while looking through there, I noticed a typo in [`test/avro/default.nix`][default] that meant it was checking the same file twice. I can clean that up now, but it might be good to figure out a better way to test the Avro CLI command eventually.

[avro]: https://github.com/target/theta-idl/tree/stage/test/avro

[default]: https://github.com/target/theta-idl/blob/stage/test/avro/default.nix

[updated]: https://github.com/target/theta-idl/blob/stage/theta/apps/Apps/Avro.hs#L125

**Comment by TikhonJelvis** [comment]
Assuming this PR can be closed in favor of #42

**Pull request closed without merging**
