### PR TITLE
Bump to GHC 9 with stack LTS-20.2

### PR DESCRIPTION
**Pull request by jack-davies**
Hi @TikhonJelvis,

I have attempted to build **theta** with GHC using the latest stackage snapshot, and am happy to report success with a couple of dependency bounds tweaks.

Additionally I've unpinned the **avro** dependency from `extra-deps` as there have been some bugfixes there.

If you're happy with this, would you have a second to merge it? Cheers!

Depends on https://github.com/psibi/streamly-bytestring/pull/28.

### CODE REVIEW

**Comment by TikhonJelvis** [comment]
Thanks!

Let me update the Nix and CI stuff to work with GHC 9 as well and then we can merge this.

**Comment by TikhonJelvis** [comment]
Okay, these changes worked for me, but looks like I'll need to move development to my personal GitHub account now that I'm no longer working at Target.

**Comment by TikhonJelvis** [comment]
Do you mind moving your PR to https://github.com/TikhonJelvis/theta-idl?

Also, when you do that, could you allow me to push commits to the PR? I believe there's a GitHub setting for that. That will let me push my Nix fixes and fix up CI before merging. (If that doesn't work, I can always do separate PRs, just seems cleaner to do everything on one.)

Thanks!

**Comment by jack-davies** [comment]
Done! https://github.com/TikhonJelvis/theta-idl/pull/1

**Pull request closed without merging**
